pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                // Aqui, o código será executado diretamente no agente Jenkins
                sh 'mvn --version'
                sh 'mvn clean package'
            }
        }
    }
}
